<?php
/**
 * Handles copying the bundled object-cache.php template into wp-content/,
 * detecting whether an existing drop-in belongs to this plugin, removing
 * it again, and keeping its server-list config file in sync with settings.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class OMM_Dropin {

	const MARKER  = 'OMM_MEMCACHED_DROPIN_MARKER';
	const VERSION = '1.0.0';

	public static function template_path() {
		return OMM_PATH . 'dropins/object-cache-dropin.php';
	}

	public static function dest_path() {
		return WP_CONTENT_DIR . '/object-cache.php';
	}

	public static function config_path() {
		return WP_CONTENT_DIR . '/omm-memcached-servers.php';
	}

	/**
	 * @return string One of: not_installed, ours, outdated, foreign
	 */
	public static function get_status() {
		$dest = self::dest_path();

		if ( ! file_exists( $dest ) ) {
			return 'not_installed';
		}

		$contents = (string) file_get_contents( $dest, false, null, 0, 4096 );

		if ( false === strpos( $contents, self::MARKER ) ) {
			return 'foreign';
		}

		if ( preg_match( '/Version:\s*([0-9.]+)/', $contents, $m ) && $m[1] !== self::VERSION ) {
			return 'outdated';
		}

		return 'ours';
	}

	private static function get_filesystem() {
		global $wp_filesystem;

		if ( ! function_exists( 'WP_Filesystem' ) ) {
			require_once ABSPATH . 'wp-admin/includes/file.php';
		}

		if ( empty( $wp_filesystem ) ) {
			WP_Filesystem();
		}

		if ( empty( $wp_filesystem ) ) {
			return new WP_Error(
				'omm_dropin_no_filesystem',
				__( 'Could not initialize the WordPress filesystem API. You may need to set FS_METHOD to "direct" in wp-config.php, or install the drop-in manually.', 'opcache-memcached-manager' )
			);
		}

		return $wp_filesystem;
	}

	/**
	 * Copy the bundled template into wp-content/object-cache.php and write
	 * the current server list alongside it.
	 *
	 * @param bool $overwrite_foreign Allow replacing a drop-in that isn't ours.
	 * @return true|WP_Error
	 */
	public static function install( $overwrite_foreign = false ) {
		$status = self::get_status();

		if ( 'foreign' === $status && ! $overwrite_foreign ) {
			return new WP_Error(
				'omm_dropin_foreign_exists',
				__( 'A different object-cache.php is already installed. Remove or back it up first, then confirm overwrite.', 'opcache-memcached-manager' )
			);
		}

		$fs = self::get_filesystem();
		if ( is_wp_error( $fs ) ) {
			return $fs;
		}

		if ( ! $fs->is_writable( WP_CONTENT_DIR ) ) {
			return new WP_Error(
				'omm_dropin_not_writable',
				sprintf( __( '%s is not writable by the web server.', 'opcache-memcached-manager' ), WP_CONTENT_DIR )
			);
		}

		$template = $fs->get_contents( self::template_path() );

		if ( false === $template ) {
			return new WP_Error( 'omm_dropin_template_missing', __( 'Could not read the bundled drop-in template.', 'opcache-memcached-manager' ) );
		}

		if ( ! $fs->put_contents( self::dest_path(), $template, FS_CHMOD_FILE ) ) {
			return new WP_Error( 'omm_dropin_write_failed', __( 'Could not write object-cache.php to wp-content/.', 'opcache-memcached-manager' ) );
		}

		$sync = self::sync_config();
		if ( is_wp_error( $sync ) ) {
			return $sync;
		}

		return true;
	}

	/**
	 * Remove the drop-in, but only if it's ours (or $force is true).
	 *
	 * @return true|WP_Error
	 */
	public static function remove( $force = false ) {
		$status = self::get_status();

		if ( 'not_installed' === $status ) {
			return true;
		}

		if ( 'foreign' === $status && ! $force ) {
			return new WP_Error(
				'omm_dropin_foreign_exists',
				__( 'The installed object-cache.php was not created by this plugin, so it will not be removed automatically.', 'opcache-memcached-manager' )
			);
		}

		$fs = self::get_filesystem();
		if ( is_wp_error( $fs ) ) {
			return $fs;
		}

		if ( $fs->exists( self::dest_path() ) && ! $fs->delete( self::dest_path() ) ) {
			return new WP_Error( 'omm_dropin_delete_failed', __( 'Could not delete object-cache.php.', 'opcache-memcached-manager' ) );
		}

		if ( $fs->exists( self::config_path() ) ) {
			$fs->delete( self::config_path() );
		}

		return true;
	}

	/**
	 * Write the currently configured Memcached servers to the config file
	 * the drop-in reads at runtime. Call whenever settings change.
	 *
	 * @return true|WP_Error
	 */
	public static function sync_config() {
		if ( ! in_array( self::get_status(), array( 'ours', 'outdated' ), true ) ) {
			return true; // Nothing to sync if the drop-in isn't ours (or isn't installed).
		}

		$fs = self::get_filesystem();
		if ( is_wp_error( $fs ) ) {
			return $fs;
		}

		$servers = OMM_Memcached::get_configured_servers();
		if ( empty( $servers ) ) {
			$servers = array( array( 'host' => '127.0.0.1', 'port' => 11211 ) );
		}

		$export = "<?php\n// Auto-generated by OPcache & Memcached Manager. Do not edit by hand.\nreturn " . var_export( $servers, true ) . ";\n";

		if ( ! $fs->put_contents( self::config_path(), $export, FS_CHMOD_FILE ) ) {
			return new WP_Error( 'omm_dropin_config_write_failed', __( 'Could not write the Memcached server config file used by the drop-in.', 'opcache-memcached-manager' ) );
		}

		return true;
	}
}
