<?php
/**
 * Settings + purge logic for the Memcached-backed page cache.
 *
 * The actual caching (serving hits, capturing misses) happens entirely in
 * the advanced-cache.php drop-in, which runs before WordPress loads. This
 * class only handles: settings, writing the config file the drop-in reads,
 * and targeted cache invalidation in response to content changes.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class OMM_PageCache {

	const OPTION_KEY   = 'omm_pagecache_settings';
	const INDEX_KEY    = 'omm_page:__index__';

	public static function init() {
		add_action( 'save_post', array( __CLASS__, 'on_save_post' ), 10, 2 );
		add_action( 'before_delete_post', array( __CLASS__, 'on_delete_post' ) );
		add_action( 'wp_trash_post', array( __CLASS__, 'on_delete_post' ) );
		add_action( 'transition_comment_status', array( __CLASS__, 'on_transition_comment_status' ), 10, 3 );
		add_action( 'comment_post', array( __CLASS__, 'on_comment_post' ), 10, 2 );
		add_action( 'switch_theme', array( __CLASS__, 'purge_all' ) );
		add_action( 'upgrader_process_complete', array( __CLASS__, 'purge_all' ) );
		add_action( 'wp_update_nav_menu', array( __CLASS__, 'purge_all' ) );
	}

	public static function default_settings() {
		return array(
			'enabled'           => false,
			'ttl'               => 3600,
			'excluded_patterns' => array(
				'#^/wp-admin#',
				'#^/wp-login\.php#',
				'#^/wp-cron\.php#',
				'#^/xmlrpc\.php#',
				'#^/wp-json#',
				'#^/feed#',
			),
		);
	}

	public static function get_settings() {
		$saved = get_option( self::OPTION_KEY, array() );
		return wp_parse_args( $saved, self::default_settings() );
	}

	public static function save_settings( $settings ) {
		update_option( self::OPTION_KEY, $settings );
		return self::sync_config();
	}

	private static function config_path() {
		return WP_CONTENT_DIR . '/omm-pagecache-config.php';
	}

	/**
	 * Write the config file the advanced-cache.php drop-in reads at
	 * runtime. Call whenever settings change, or after installing the
	 * drop-in.
	 *
	 * @return true|WP_Error
	 */
	public static function sync_config() {
		if ( ! in_array( OMM_PageCache_Dropin::get_status(), array( 'ours', 'outdated' ), true ) ) {
			return true; // Nothing to sync if the drop-in isn't ours (or isn't installed).
		}

		global $wp_filesystem;
		if ( ! function_exists( 'WP_Filesystem' ) ) {
			require_once ABSPATH . 'wp-admin/includes/file.php';
		}
		if ( empty( $wp_filesystem ) ) {
			WP_Filesystem();
		}
		if ( empty( $wp_filesystem ) ) {
			return new WP_Error( 'omm_pagecache_no_filesystem', __( 'Could not initialize the WordPress filesystem API.', 'opcache-memcached-manager' ) );
		}

		$settings = self::get_settings();
		$config   = array(
			'enabled'           => ! empty( $settings['enabled'] ),
			'ttl'               => (int) $settings['ttl'],
			'excluded_patterns' => array_values( array_filter( array_map( 'trim', (array) $settings['excluded_patterns'] ) ) ),
		);

		$export = "<?php\n// Auto-generated by OPcache & Memcached Manager. Do not edit by hand.\nreturn " . var_export( $config, true ) . ";\n";

		if ( ! $wp_filesystem->put_contents( self::config_path(), $export, FS_CHMOD_FILE ) ) {
			return new WP_Error( 'omm_pagecache_config_write_failed', __( 'Could not write the page cache config file used by the drop-in.', 'opcache-memcached-manager' ) );
		}

		return true;
	}

	/**
	 * Must exactly match omm_pagecache_build_key() in the drop-in template.
	 */
	public static function build_key( $url ) {
		$parts  = wp_parse_url( $url );
		$scheme = $parts['scheme'] ?? 'http';
		$host   = $parts['host'] ?? '';
		$path   = '/' . ltrim( $parts['path'] ?? '/', '/' );

		return 'omm_page:' . md5( strtolower( $scheme ) . '://' . strtolower( $host ) . $path );
	}

	/**
	 * Purge a single URL from the page cache.
	 *
	 * @return true|WP_Error
	 */
	public static function purge_url( $url ) {
		$mc = OMM_Memcached::get_instance();
		if ( is_wp_error( $mc ) ) {
			return $mc;
		}

		$key = self::build_key( $url );
		$mc->delete( $key );

		$index = $mc->get( self::INDEX_KEY );
		if ( is_array( $index ) && isset( $index[ $key ] ) ) {
			unset( $index[ $key ] );
			$mc->set( self::INDEX_KEY, $index, 0 );
		}

		return true;
	}

	/**
	 * Purge several URLs at once.
	 *
	 * @return true|WP_Error
	 */
	public static function purge_urls( array $urls ) {
		$mc = OMM_Memcached::get_instance();
		if ( is_wp_error( $mc ) ) {
			return $mc;
		}

		$index = $mc->get( self::INDEX_KEY );
		if ( ! is_array( $index ) ) {
			$index = array();
		}

		foreach ( array_unique( $urls ) as $url ) {
			$key = self::build_key( $url );
			$mc->delete( $key );
			unset( $index[ $key ] );
		}

		$mc->set( self::INDEX_KEY, $index, 0 );

		return true;
	}

	/**
	 * Purge every currently tracked page-cache entry. Deliberately never
	 * calls Memcached::flush(), since that would also wipe the object
	 * cache (and anything else) sharing the same server pool.
	 *
	 * @return true|WP_Error
	 */
	public static function purge_all() {
		$mc = OMM_Memcached::get_instance();
		if ( is_wp_error( $mc ) ) {
			return $mc;
		}

		$index = $mc->get( self::INDEX_KEY );

		if ( is_array( $index ) ) {
			foreach ( array_keys( $index ) as $key ) {
				$mc->delete( $key );
			}
		}

		$mc->set( self::INDEX_KEY, array(), 0 );

		return true;
	}

	/**
	 * How many page cache entries are currently tracked.
	 */
	public static function get_cached_count() {
		$mc = OMM_Memcached::get_instance();
		if ( is_wp_error( $mc ) ) {
			return 0;
		}
		$index = $mc->get( self::INDEX_KEY );
		return is_array( $index ) ? count( $index ) : 0;
	}

	/* -----------------------------------------------------------------
	 * Targeted purge: figure out which URLs a content change affects.
	 * ------------------------------------------------------------- */

	private static function urls_for_post( $post_id ) {
		$post = get_post( $post_id );
		if ( ! $post || 'publish' !== $post->post_status ) {
			return array();
		}

		$urls = array();

		$permalink = get_permalink( $post );
		if ( $permalink ) {
			$urls[] = $permalink;
		}

		$urls[] = home_url( '/' );

		$page_for_posts = (int) get_option( 'page_for_posts' );
		if ( $page_for_posts ) {
			$posts_page_url = get_permalink( $page_for_posts );
			if ( $posts_page_url ) {
				$urls[] = $posts_page_url;
			}
		}

		$author_url = get_author_posts_url( $post->post_author );
		if ( $author_url ) {
			$urls[] = $author_url;
		}

		$timestamp = strtotime( $post->post_date );
		if ( $timestamp ) {
			$urls[] = get_year_link( gmdate( 'Y', $timestamp ) );
			$urls[] = get_month_link( gmdate( 'Y', $timestamp ), gmdate( 'm', $timestamp ) );
			$urls[] = get_day_link( gmdate( 'Y', $timestamp ), gmdate( 'm', $timestamp ), gmdate( 'd', $timestamp ) );
		}

		foreach ( get_object_taxonomies( $post->post_type ) as $taxonomy ) {
			$terms = get_the_terms( $post, $taxonomy );
			if ( is_array( $terms ) ) {
				foreach ( $terms as $term ) {
					$link = get_term_link( $term );
					if ( ! is_wp_error( $link ) ) {
						$urls[] = $link;
					}
				}
			}
		}

		return array_filter( $urls );
	}

	public static function on_save_post( $post_id, $post ) {
		if ( wp_is_post_revision( $post_id ) || wp_is_post_autosave( $post_id ) ) {
			return;
		}

		if ( ! is_post_type_viewable( $post->post_type ) ) {
			return;
		}

		$urls = self::urls_for_post( $post_id );
		if ( ! empty( $urls ) ) {
			self::purge_urls( $urls );
		}
	}

	public static function on_delete_post( $post_id ) {
		self::on_save_post( $post_id, get_post( $post_id ) );
	}

	public static function on_transition_comment_status( $new_status, $old_status, $comment ) {
		if ( 'approved' === $new_status || 'approved' === $old_status ) {
			$urls = self::urls_for_post( $comment->comment_post_ID );
			if ( ! empty( $urls ) ) {
				self::purge_urls( $urls );
			}
		}
	}

	public static function on_comment_post( $comment_id, $comment_approved ) {
		if ( 1 === (int) $comment_approved ) {
			$comment = get_comment( $comment_id );
			if ( $comment ) {
				$urls = self::urls_for_post( $comment->comment_post_ID );
				if ( ! empty( $urls ) ) {
					self::purge_urls( $urls );
				}
			}
		}
	}
}
